#requires -Version 5.1
<#
.SYNOPSIS
    Generate server release and handover documentation (Markdown + Word/PDF).

.PARAMETER ServerName
    Target server hostname.

.PARAMETER BuildDate
    Build or release date.

.PARAMETER Applications
    Application list.

.PARAMETER Ports
    Open ports / firewall rules.

.PARAMETER Dependencies
    Upstream/downstream dependencies.

.PARAMETER OutputDirectory
    Folder for generated documents.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$ServerName,

    [datetime]$BuildDate = (Get-Date),

    [string[]]$Applications = @(),

    [string[]]$Ports = @(),

    [string[]]$Dependencies = @(),

    [string]$OwnerTeam = 'Infrastructure Operations',

    [string]$Environment = 'Production',

    [string]$OutputDirectory = (Join-Path $PSScriptRoot 'output')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $OutputDirectory)) {
    $null = New-Item -ItemType Directory -Path $OutputDirectory -Force
}

$safeName = $ServerName -replace '[^\w\-]', '-'
$stamp = Get-Date -Format 'yyyyMMdd'
$mdPath = Join-Path $OutputDirectory ("{0}-Release-Handover-{1}.md" -f $safeName, $stamp)
$docxPath = Join-Path $OutputDirectory ("{0}-Release-Handover-{1}.docx" -f $safeName, $stamp)
$pdfPath = Join-Path $OutputDirectory ("{0}-Release-Handover-{1}.pdf" -f $safeName, $stamp)

$appList = if ($Applications.Count) { ($Applications | ForEach-Object { "- $_" }) -join "`n" } else { '- (none specified)' }
$portList = if ($Ports.Count) { ($Ports | ForEach-Object { "- $_" }) -join "`n" } else { '- (none specified)' }
$depList = if ($Dependencies.Count) { ($Dependencies | ForEach-Object { "- $_" }) -join "`n" } else { '- (none specified)' }

$markdown = @"
# Server Release and Handover Document

**Server:** $ServerName  
**Environment:** $Environment  
**Build Date:** $($BuildDate.ToString('yyyy-MM-dd'))  
**Document Date:** $(Get-Date -Format 'yyyy-MM-dd')  
**Owner Team:** $OwnerTeam  

---

## 1. Executive Summary

This document provides operational handover details for **$ServerName** following build and validation. It is intended for NOC, server, and application support teams.

## 2. Server Overview

| Field | Value |
|-------|-------|
| Hostname | $ServerName |
| Environment | $Environment |
| Build Date | $($BuildDate.ToString('yyyy-MM-dd')) |
| Primary Owner | $OwnerTeam |

## 3. Installed Applications

$appList

## 4. Network and Ports

$portList

## 5. Dependencies

$depList

## 6. Operational Contacts

| Role | Contact |
|------|---------|
| Infrastructure Lead | infra-leads@example.com |
| Application Owner | app-owner@example.com |
| On-Call | oncall@example.com |

## 7. Monitoring and Alerting

- SolarWinds node: $ServerName
- CrowdStrike sensor installed and reporting
- Event log forwarding: enabled (verify in SIEM)
- Patching group: Production-Monthly

## 8. Backup and Recovery

- Backup policy: Daily incremental, weekly full
- RTO target: 4 hours
- RPO target: 24 hours
- Last successful backup: _verify before sign-off_

## 9. Access and Security

- RDP/jump access via privileged access workstation
- Local admin restricted to break-glass account
- CIS hardening applied: Level 1 minimum
- Change record: _attach CR number_

## 10. Known Issues and Caveats

- None at handover (update if discovered during hypercare)

## 11. Rollback Plan

1. Stop application services on $ServerName
2. Revert DNS/load balancer to previous node if applicable
3. Restore VM from last known-good snapshot or backup
4. Notify stakeholders and update change record

## 12. Sign-Off

| Role | Name | Date | Signature |
|------|------|------|-----------|
| Build Engineer | | | |
| Operations Lead | | | |
| Application Owner | | | |

---

*Generated by New-ServerReleaseDoc.ps1*
"@

Set-Content -Path $mdPath -Value $markdown -Encoding UTF8
Write-Host "Markdown: $mdPath" -ForegroundColor Green

# Word export via Word COM if available
try {
    $word = New-Object -ComObject Word.Application
    $word.Visible = $false
    $doc = $word.Documents.Add()

    foreach ($line in ($markdown -split "`n")) {
        if ($line -match '^# (.+)$') {
            $range = $doc.Content
            $range.Collapse(0)
            $range.Text = $Matches[1] + [Environment]::NewLine
            $range.Style = 'Heading 1'
        }
        elseif ($line -match '^## (.+)$') {
            $range = $doc.Content
            $range.Collapse(0)
            $range.Text = $Matches[1] + [Environment]::NewLine
            $range.Style = 'Heading 2'
        }
        else {
            $range = $doc.Content
            $range.Collapse(0)
            $range.Text = $line + [Environment]::NewLine
        }
    }

    $doc.SaveAs([ref]$docxPath)
    $doc.ExportAsFixedFormat($pdfPath, 17)
    $doc.Close()
    $word.Quit()

    Write-Host "Word:   $docxPath" -ForegroundColor Green
    Write-Host "PDF:    $pdfPath" -ForegroundColor Green
}
catch {
    Write-Warning "Word COM export skipped (requires Microsoft Word): $($_.Exception.Message)"
    Write-Host "Use the Markdown file or pandoc to generate DOCX/PDF on this machine."
}

Write-Host "Handover document package complete." -ForegroundColor Cyan
